name: update data and deploy

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - 'standalone'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update-course:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: standalone

      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10'
      #
      # - name: "Install crawler's dependencies"
      #   run: |
      #     pip install Scrapy
      # 
      # - name: "Execute the crawler"
      #   working-directory: ./crawler
      #   run: |
      #     scrapy crawl courses

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: "Install the website's dependencies"
        run: |
          npm ci
          npm run build
    
      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
